platform: x64

branches:
    only:
        - master

environment:

    matrix:
        - PYTHON: "C:\\Python36-x64"

install:
    - "%PYTHON%\\python.exe -m pip install wheel"

test_script:
    - "%PYTHON%\\python.exe setup.py test"

after_test:
    - "%PYTHON%\\python.exe setup.py bdist_wheel"