platform: x64

branches:
    only:
        - master

environment:
    matrix:
        - PYTHON: "C:\\Python36-x64"
        - PYTHON: "C:\\Python36"

build: off

install:
    - "pip install --disable-pip-version-check --user --upgrade pip"
    - "%CMD_IN_ENV% pip install -r requirements.txt"
    - "%PYTHON%\\python.exe -m pip install wheel"

test_script:
    - "%PYTHON%\\python.exe setup.py test"

after_test:
    - "%PYTHON%\\python.exe setup.py bdist_wheel"